version: "3.9"
services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: freighter-redis
    hostname: freighter-redis
    restart: always
    networks:
      - freighter
    ports:
      - 6379:6379

networks:
  freighter:
    driver: bridge
